# -*- coding: utf-8 -*-
QUEUE_NAME = 'collective.azipfele.zip'
ZIPDIRKEY = 'COLLECTIVE_AZIPFELE_ZIPS'
ZIPNGINXKEY = 'COLLECTIVE_AZIPFELE_NGINX'
ZIPSTATE_MEMCACHEDSERVER = 'COLLECTIVE_AZIPFELE_MEMCACHED'
